# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-17 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_bcsignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcsignal',
            name='browser',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bcsignal',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bcsignal',
            name='feature',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bcsignal',
            name='links',
            field=models.TextField(blank=True),
        ),
    ]
